server:
  port: 8080
#secret key - should be encrypted
jwt:
  secret: secretkey

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service-id
          uri: lb:/auth-service
          predicates:
            - Path=/auth/**
        - id:  articles-service-id
          uri: lb:/articles-service
          predicates:
            - Path=/articles/**
          filters:
            - Auth

eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

